# Generated by Django 2.1.3 on 2018-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(max_length=20, verbose_name='报警类型')),
                ('description', models.CharField(max_length=20, verbose_name='报警描述')),
                ('alarm_rule', models.CharField(max_length=20, verbose_name='发送规则')),
            ],
            options={
                'verbose_name': '邮件规则',
                'verbose_name_plural': '邮件规则',
            },
        ),
        migrations.CreateModel(
            name='MailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('sent', models.BooleanField(default=False, verbose_name='已发送')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '邮件信息',
                'verbose_name_plural': '邮件信息',
            },
        ),
        migrations.CreateModel(
            name='MailOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20, verbose_name='游戏')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('alarms', models.ManyToManyField(to='server_mail.AlarmRule', verbose_name='操作规则')),
            ],
            options={
                'verbose_name': '邮件操作',
                'verbose_name_plural': '邮件操作',
            },
        ),
    ]
