# Generated by Django 2.1.3 on 2018-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinfo',
            name='mail_types',
            field=models.ManyToManyField(to='server_mail.AlarmRule', verbose_name='邮件类型'),
        ),
    ]
