# Generated by Django 2.1.3 on 2018-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0002_mailinfo_mail_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinfo',
            name='game',
            field=models.CharField(default='', max_length=20, verbose_name='游戏'),
            preserve_default=False,
        ),
    ]
