# Generated by Django 2.1.3 on 2018-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0003_mailinfo_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinfo',
            options={'ordering': ['-create_date'], 'verbose_name': '邮件信息', 'verbose_name_plural': '邮件信息'},
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='mail_types',
            field=models.ManyToManyField(related_name='mail_type', to='server_mail.AlarmRule', verbose_name='邮件类型'),
        ),
        migrations.AlterField(
            model_name='mailoperation',
            name='alarms',
            field=models.ManyToManyField(related_name='alarm', to='server_mail.AlarmRule', verbose_name='操作规则'),
        ),
    ]
