# Generated by Django 2.1.3 on 2018-12-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0004_auto_20181210_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinfo',
            name='mail_types',
            field=models.ManyToManyField(to='server_mail.AlarmRule', verbose_name='邮件类型'),
        ),
        migrations.AlterField(
            model_name='mailoperation',
            name='alarms',
            field=models.ManyToManyField(to='server_mail.AlarmRule', verbose_name='操作规则'),
        ),
    ]
