# Generated by Django 2.1.3 on 2018-12-11 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0005_auto_20181210_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailoperation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加日期'),
            preserve_default=False,
        ),
    ]
