# Generated by Django 2.1.3 on 2018-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0006_mailoperation_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='邮件主题')),
                ('mail_template', models.CharField(default='', max_length=100, verbose_name='邮件模板')),
                ('json_args', models.CharField(default='', max_length=50, verbose_name='前端参数')),
                ('template_kwargs', models.CharField(default='', max_length=50, verbose_name='模板参数')),
                ('alarms', models.ManyToManyField(to='server_mail.AlarmRule', verbose_name='报警类型')),
            ],
            options={
                'verbose_name': '邮件生成',
                'verbose_name_plural': '邮件生成',
            },
        ),
        migrations.AlterModelOptions(
            name='mailoperation',
            options={'ordering': ['-created_date'], 'verbose_name': '邮件操作', 'verbose_name_plural': '邮件操作'},
        ),
    ]
