# Generated by Django 2.1.3 on 2018-12-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0008_auto_20181215_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoperation',
            name='send_rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_mail.SendRule'),
        ),
    ]
