# Generated by Django 2.1.3 on 2018-12-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0009_auto_20181215_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailgenerator',
            name='alarms',
        ),
        migrations.RemoveField(
            model_name='alarmrule',
            name='alarm_rule',
        ),
        migrations.AddField(
            model_name='alarmrule',
            name='json_args',
            field=models.CharField(default='', max_length=50, verbose_name='前端参数'),
        ),
        migrations.AddField(
            model_name='alarmrule',
            name='send_rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_mail.SendRule', verbose_name='发送规则'),
        ),
        migrations.AddField(
            model_name='mailinfo',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='mailinfo',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='区服'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='game',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='mailoperation',
            name='game',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='mailoperation',
            name='send_rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_mail.SendRule', verbose_name='发送规则'),
        ),
        migrations.DeleteModel(
            name='MailGenerator',
        ),
    ]
