# Generated by Django 2.1.3 on 2018-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0010_auto_20181217_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmrule',
            name='mail_template',
            field=models.CharField(default='', max_length=100, verbose_name='邮件模板'),
        ),
        migrations.AddField(
            model_name='alarmrule',
            name='template_kwargs',
            field=models.CharField(default='', max_length=50, verbose_name='模板参数'),
        ),
    ]
