# Generated by Django 2.1.3 on 2018-12-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0011_auto_20181217_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmrule',
            name='mail_template',
        ),
    ]
