# Generated by Django 2.1.3 on 2018-12-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_mail', '0012_remove_alarmrule_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoperation',
            name='send_rules',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server_mail.SendRule', verbose_name='发送规则'),
        ),
    ]
