# Generated by Django 2.1.3 on 2019-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='json_args',
            field=models.CharField(max_length=50, verbose_name='前端参数'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='template_kwargs',
            field=models.CharField(max_length=50, verbose_name='模板参数'),
        ),
    ]
