# Generated by Django 2.1.3 on 2019-01-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailoperation',
            old_name='send_rules',
            new_name='rules',
        ),
    ]
