# Generated by Django 2.1.3 on 2019-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0002_auto_20190128_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='receivers',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='收件人列表'),
        ),
    ]
