# Generated by Django 2.1.3 on 2019-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0003_auto_20190128_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='receivers_by_games',
            field=models.BooleanField(default=False, verbose_name='是否按游戏区分'),
        ),
    ]
