# Generated by Django 2.1.3 on 2019-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0005_auto_20190128_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoperation',
            name='receivers',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='content',
            field=models.CharField(max_length=100, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='game',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='mailinfo',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='区服'),
        ),
    ]
