# Generated by Django 2.1.3 on 2019-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_alarm', '0006_auto_20190213_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoperation',
            name='receivers',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='收件人'),
        ),
    ]
